# Generated by Django 5.0.6 on 2024-05-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdFerremax', '0002_customuser_carrito_productocarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
