# Generated by Django 5.0.6 on 2024-05-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdFerremax', '0005_webpaytransaction_webpaytransactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpaytransaction',
            name='token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
