# Generated by Django 5.0.6 on 2024-07-06 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bdFerremax", "0009_pedido_pedidoitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedidoitem",
            name="pedido",
        ),
        migrations.RemoveField(
            model_name="pedidoitem",
            name="producto",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
        migrations.DeleteModel(
            name="PedidoItem",
        ),
    ]
