# Generated by Django 5.0.6 on 2024-07-08 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bdFerremax",
            "0010_remove_pedidoitem_pedido_remove_pedidoitem_producto_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("procesando", "Procesando"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                        ],
                        default="enviando",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "transaccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bdFerremax.webpaytransaction",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
