# Generated by Django 5.0.6 on 2024-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdFerremax", "0012_rename_transaccion_pedido_webpay_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("preparando", "Preparando"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                ],
                default="preparando",
                max_length=10,
            ),
        ),
    ]
