# Generated by Django 5.0.6 on 2024-07-12 23:04

import django.db.models.deletion
from django.db import migrations, models

def create_default_metodo_pago(apps, schema_editor):
    MetodoPago = apps.get_model('bdFerremax', 'MetodoPago')
    MetodoPago.objects.create(id=1, nombre='Debito')

class Migration(migrations.Migration):
    dependencies = [
        ("bdFerremax", "0014_producto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="pedido",
            name="webpay_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdFerremax.webpaytransaction",
            ),
        ),
        migrations.RunPython(create_default_metodo_pago),  # Agregar esta línea
        migrations.AddField(
            model_name="pedido",
            name="metodo_pago",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdFerremax.metodopago",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bdFerremax.sucursal",
            ),
        ),
    ]
