# Generated by Django 5.0.6 on 2024-07-12 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bdFerremax",
            "0015_metodopago_sucursal_alter_pedido_webpay_transaction_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="metodo_pago",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdFerremax.metodopago",
            ),
        ),
    ]
