# Generated by Django 5.0.6 on 2024-07-15 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdFerremax", "0016_alter_pedido_metodo_pago"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="fecha_creacion",
            new_name="fecha_pedido",
        ),
        migrations.RenameField(
            model_name="pedido",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="webpay_transaction",
        ),
        migrations.AddField(
            model_name="pedido",
            name="direccion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="envio",
            field=models.CharField(
                choices=[("domicilio", "Domicilio"), ("sucursal", "Sucursal")],
                default="domicilio",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="voucher",
            field=models.FileField(blank=True, null=True, upload_to="vouchers/"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="metodo_pago",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bdFerremax.metodopago"
            ),
        ),
    ]
