# Generated by Django 5.0.6 on 2024-07-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdFerremax", "0019_productopedido_pedido_productos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="productos",
        ),
        migrations.DeleteModel(
            name="ProductoPedido",
        ),
        migrations.AddField(
            model_name="pedido",
            name="productos",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
    ]
