# Generated by Django 5.0.6 on 2024-07-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdFerremax", "0021_remove_pedido_productos_productopedido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("preparando", "Preparando"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                ],
                default="preparando",
                max_length=20,
            ),
        ),
    ]
